[build]
builder = "NIXPACKS"
buildCommand = "./build.sh"

[deploy]
startCommand = "gunicorn --chdir sylistock --bind 0.0.0.0:$PORT --workers 3 sylistock.wsgi:application"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PYTHONPATH = "/app/sylistock"
DEBUG = "False"
ALLOWED_HOSTS = "*.railway.app,localhost,127.0.0.1"

[[services]]
name = "sylistockapp"

[services.web]
source = "."
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
