services:
  - type: web
    name: sylistockapp
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python sylistock/manage.py collectstatic --noinput
      python sylistock/manage.py migrate
    startCommand: gunicorn sylistock.wsgi:application --chdir sylistock --bind 0.0.0.0:$PORT --workers 3
    healthCheckPath: /
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*.onrender.com"
      - key: PYTHONPATH
        value: "/opt/render/project/src/sylistock"
      - key: DATABASE_URL
        fromDatabase:
          name: sylidb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
    autoDeploy: true
