services:
  - type: web
    name: sylistockapp
    runtime: python312
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn sylistock.wsgi --chdir sylistock
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*.onrender.com"
    autoDeploy: true

