name: sylistock_mobile
description: A small Flutter client for Sylis stock app (mobile scanner client).
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^3.0.0
  flutter_datawedge: ^3.2.0
  device_info_plus: ^10.1.0
  mobile_scanner: ^5.0.0 # For the phone camera fallback
  dio: ^5.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  what3words: ^3.2.0
  file_picker: ^8.0.0
  camera: ^0.10.5
  permission_handler: ^11.0.1
  image_picker: ^1.0.4
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  mockito: ^5.4.4

flutter:
  uses-material-design: true
